### ISSUE TITLE
1.16.1 Loading Issue.

### ISSUE THREAD

**Issue by MinecraftAdmin** [TownyAdvanced/TownyFlight#39]
Plugin fails to load on Paper 1.16.1 with this error:
```
[TownyFlight] Enabling TownyFlight v1.6.2
[ERROR] Error occurred while enabling TownyFlight v1.6.2 (Is it up to date?)
[RAW] java.lang.NoClassDefFoundError: com/palmergames/bukkit/util/Version
[RAW] 	at com.gmail.llmdlio.townyflight.TownyFlight.townyVersionCheck(TownyFlight.java:98) ~[?:?]
[RAW] 	at com.gmail.llmdlio.townyflight.TownyFlight.onEnable(TownyFlight.java:85) ~[?:?]
[RAW] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-116]
[RAW] 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-116]
[RAW] 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-116]
[RAW] 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-116]
[RAW] 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-116]
[RAW] 	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-116]
[RAW] 	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-116]
[RAW] 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-116]
[RAW] 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-116]
[RAW] 	at java.lang.Thread.run(Thread.java:834) [?:?]
[RAW] Caused by: java.lang.ClassNotFoundException: com.palmergames.bukkit.util.Version
[RAW] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
[RAW] 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.1.jar:git-Paper-116]
[RAW] 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.1.jar:git-Paper-116]
[RAW] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
[RAW] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
[RAW] 	... 12 more
[TownyFlight] Disabling TownyFlight v1.6.2
[TownyFlight] TownyFlight Disabled.
```
### Versions/Files

Towny Version (use '/towny v' in game) : 0.96.2.0
TownyFlight Version : 1.6.2
Link to pastebin.com with full server startup from the latest.log : https://pastebin.com/raw/P5UKLed5
Link to pastebin.com with TownyFlight config.yml : https://pastebin.com/raw/zvVJRp3w

**Comment by LlmDl** [comment]
TF 1.6.2 is meant for newer versions of Towny. Use TF 1.6.1.
